---
disks:
  - disks/disk1
  - disks/disk2
  - disks/disk3
  - disks/disk4
  - disks/disk5
etcd_config:
  enable: true
  etcd_nodes:
    - http://127.0.0.1:12379
    - http://127.0.0.1:22379
    - http://127.0.0.1:32379